# Generated by Django 3.0.5 on 2021-09-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crap', '0002_coviddata_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='last_updated',
            field=models.CharField(max_length=50),
        ),
    ]
