# Generated by Django 3.0.5 on 2021-09-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crap', '0003_auto_20210912_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coviddata',
            name='last_updated',
            field=models.CharField(max_length=60),
        ),
    ]
